<?php



//hook_init()
function hello_init(){
    //drupal_set_message("hello");
}

//hook_menu()
function hello_menu(){
    $items =array();

    $items['hellopage'] = array(

        'title'=>'My Hello Page',
        'description' => 'Hello users',
        'page callback' =>'drupal_get_form',
        'page arguments' =>array('hello_form'),
        'access callback'=>'user_access',
        'access arguments'=>array('access content'),
        'type'=>MENU_NORMAL_ITEM

);


    return $items;


}


//hook_form()
function hello_form() {


    $form['title'] = array(
        '#type' => 'textfield',
        '#title' => 'Title',
        '#default_value' => '',
        '#required' => TRUE,
        '#weight' => -5,
    );

    $form['field1'] = array(
        '#type' => 'textfield',
        '#title' => t('Custom field'),
        '#default_value' => '',
        '#maxlength' => 127,
        '#required' => TRUE,
    );
    $form['selectbox'] = array(
        '#type' => 'select',
        '#title' => t('Select box'),
        '#default_value' => 1,
        '#options' => array(
            1 => 'Option A',
            2 => 'Option B',
            3 => 'Option C',
        ),
        '#description' => t('Choose an option.'),
    );
    $form['submit'] = array(

        '#type' =>'submit',
        '#value'=>'Submit'
    );

    return $form;
}

function hello_ajaxCallHandler(){

    $name = $_GET['name'];

    echo "Hello " . $name;
}

function hello_showHelloForm(){

    $form = array();

    $form['name'] = array(


        '#type'=>'textfield',
        '#title'=>'Enter your name'
    );

    $form['submit'] = array(

        '#type' =>'submit',
        '#value'=>'Submit'
    );

    $form['#submit'][]='hello_showHelloForm_submit';

    //without using form api

    $form['#suffix']='<input type="button" id ="submitAjaxButton" value="Submit with Ajax"><br>
<div id ="msg-display-area">

</div>';

    drupal_add_js(drupal_get_path('module','hello')."hello/js");

    return $form;

}

function hello_showHelloForm_submit($form,&$form_state){

    if($form_state['values']['name'] == ""){
        form_set_error('name',"Name can not be empty");
    }else{
        drupal_set_message("Hello ".$form_state['values']['name']." !");
    }
}